# Copyright 2022 <mzh.scnu@qq.com>. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# storage
path: /tmp/bakemono-test.vol
size_mb: 4096
avg_chunk_size: 8000

schema: http                        # support http and https
port: 80                            # port for balancer
ssl_certificate:
ssl_certificate_key:
location:                   
  - pattern: /

# upstream 
tcp_health_check: true
health_check_interval: 10           # health check interval (second)
upstream:                      
  proxy_pass:                  
  - "http://10.62.216.7"
  - "http://10.62.216.8"
  balance_mode: consistent-hash     # load balancing algorithm

# log
access_log_path: logs/access.log
zap_config: 
  level: "debug"
  encoding: "console"
  development: true
  encoderConfig:
    messageKey: "Msg"
    levelKey: "Level"
    timeKey: "Time"
    nameKey: "Name"
    callerKey: "Caller"
    stacktraceKey: "St"
    levelEncoder: "capital"
    timeEncoder: "iso8601"
    durationEncoder: "string"
    callerEncoder: "short"
  outputPaths:
    - "stdout"
    - "logs/bakemono.log"
  errorOutputPaths:
    - "stderr"
    - "logs/error.log"